from datetime import datetime, timezone


[
    {
        "fixture_id": "217542",
        "fixture_date": datetime.date(2025, 8, 7),
        "first_post_time": datetime.datetime(2025, 8, 7, 19, 10, tzinfo=tzutc()),
        "race_count": 8,
        "temperature_fahrenheit": 66,
        "temperature_celsius": 18.9,
        "track_id": "3094",
        "tpd_meeting_id": 0,
        "race_data": [
            {
                "race_id": "6042447",
                "race_number": "2",
                "runner_count": 7,
                "post_time": datetime.datetime(2025, 8, 7, 19, 43, tzinfo=tzutc()),
                "estimated_post_time": datetime.datetime(
                    2025, 8, 7, 19, 43, tzinfo=tzutc()
                ),
                "off_time": None,
                "weather": "cloudy",
                "going": "fast",
                "race_name": "Race 2",
                "race_status": "GoingDown",
                "overround": "1.21",
                "overround_selection": "standard",
                "race_result": None,
                "surface": "",
                "tpd_race_id": 0,
                "race_status_history_data": [
                    {
                        "race_id": "6042447",
                        "status": "Dormant",
                        "timestamp": datetime.datetime(
                            2025, 8, 6, 9, 31, 16, tzinfo=tzutc()
                        ),
                    }
                ],
                "entry_data": [
                    {
                        "entry_id": "20658864",
                        "start_number": "1",
                        "entry_program_number": "1",
                        "start_position": "1",
                        "coupled_indicator": 0,
                        "decoupled_number": "1",
                        "horse_id": "1099713",
                        "horse_name": "Arrakasta Izan",
                        "entry_status": 1,
                        "equipment_code": "",
                        "equipment_description": "",
                        "weight_value": "122",
                        "weight_unit": "lbs",
                        "jockey_id": "148119",
                        "jockey_name": "Jalon L. Samuel",
                        "starting_price_fraction": "",
                        "starting_price_percentage": 0,
                        "fav_pos": None,
                        "fav_joint": None,
                        "final_position": "",
                        "dead_heat": None,
                        "disqualified": False,
                        "amended_position": None,
                        "tpd_runner_id": 0,
                        "historical_price_data": [
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:35:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:36:26+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658865",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:32:25+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658867",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658867",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:35:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:30:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:30:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                        ],
                    },
                    {
                        "entry_id": "20658865",
                        "start_number": "2",
                        "entry_program_number": "2",
                        "start_position": "2",
                        "coupled_indicator": 0,
                        "decoupled_number": "2",
                        "horse_id": "1119099",
                        "horse_name": "King Putt",
                        "entry_status": 1,
                        "equipment_code": "",
                        "equipment_description": "",
                        "weight_value": "118",
                        "weight_unit": "lbs",
                        "jockey_id": "169800",
                        "jockey_name": "Desean Bynoe",
                        "starting_price_fraction": "",
                        "starting_price_percentage": 0,
                        "fav_pos": None,
                        "fav_joint": None,
                        "final_position": "",
                        "dead_heat": None,
                        "disqualified": False,
                        "amended_position": None,
                        "tpd_runner_id": 0,
                        "historical_price_data": [
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:35:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:36:26+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658865",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:32:25+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658867",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658867",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:35:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:30:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:30:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                        ],
                    },
                    {
                        "entry_id": "20658866",
                        "start_number": "3",
                        "entry_program_number": "3",
                        "start_position": "3",
                        "coupled_indicator": 0,
                        "decoupled_number": "3",
                        "horse_id": "1068431",
                        "horse_name": "Quandale",
                        "entry_status": 1,
                        "equipment_code": "",
                        "equipment_description": "",
                        "weight_value": "122",
                        "weight_unit": "lbs",
                        "jockey_id": "0",
                        "jockey_name": "Austin Adams",
                        "starting_price_fraction": "",
                        "starting_price_percentage": 0,
                        "fav_pos": None,
                        "fav_joint": None,
                        "final_position": "",
                        "dead_heat": None,
                        "disqualified": False,
                        "amended_position": None,
                        "tpd_runner_id": 0,
                        "historical_price_data": [
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:35:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:36:26+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658865",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:32:25+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658867",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658867",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:35:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:30:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:30:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                        ],
                    },
                    {
                        "entry_id": "20658867",
                        "start_number": "4",
                        "entry_program_number": "4",
                        "start_position": "4",
                        "coupled_indicator": 0,
                        "decoupled_number": "4",
                        "horse_id": "1126851",
                        "horse_name": "Nikinzie",
                        "entry_status": 1,
                        "equipment_code": "",
                        "equipment_description": "",
                        "weight_value": "120",
                        "weight_unit": "lbs",
                        "jockey_id": "171352",
                        "jockey_name": "Slade Jones",
                        "starting_price_fraction": "",
                        "starting_price_percentage": 0,
                        "fav_pos": None,
                        "fav_joint": None,
                        "final_position": "",
                        "dead_heat": None,
                        "disqualified": False,
                        "amended_position": None,
                        "tpd_runner_id": 0,
                        "historical_price_data": [
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:35:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:36:26+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658865",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:32:25+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658867",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658867",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:35:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:30:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:30:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                        ],
                    },
                    {
                        "entry_id": "20658868",
                        "start_number": "5",
                        "entry_program_number": "5",
                        "start_position": "5",
                        "coupled_indicator": 0,
                        "decoupled_number": "5",
                        "horse_id": "1118540",
                        "horse_name": "Last Ride",
                        "entry_status": 1,
                        "equipment_code": "",
                        "equipment_description": "",
                        "weight_value": "120",
                        "weight_unit": "lbs",
                        "jockey_id": "148509",
                        "jockey_name": "Skye Chernetz",
                        "starting_price_fraction": "",
                        "starting_price_percentage": 0,
                        "fav_pos": None,
                        "fav_joint": None,
                        "final_position": "",
                        "dead_heat": None,
                        "disqualified": False,
                        "amended_position": None,
                        "tpd_runner_id": 0,
                        "historical_price_data": [
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:35:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:36:26+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658865",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:32:25+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658867",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658867",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:35:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:30:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:30:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                        ],
                    },
                    {
                        "entry_id": "20658869",
                        "start_number": "6",
                        "entry_program_number": "6",
                        "start_position": "6",
                        "coupled_indicator": 0,
                        "decoupled_number": "6",
                        "horse_id": "1165584",
                        "horse_name": "Ashwood",
                        "entry_status": 1,
                        "equipment_code": "",
                        "equipment_description": "",
                        "weight_value": "120",
                        "weight_unit": "lbs",
                        "jockey_id": "145189",
                        "jockey_name": "Jeffrey Ian Alderson",
                        "starting_price_fraction": "",
                        "starting_price_percentage": 0,
                        "fav_pos": None,
                        "fav_joint": None,
                        "final_position": "",
                        "dead_heat": None,
                        "disqualified": False,
                        "amended_position": None,
                        "tpd_runner_id": 0,
                        "historical_price_data": [
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:35:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:36:26+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658865",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:32:25+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658867",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658867",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:35:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:30:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:30:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                        ],
                    },
                    {
                        "entry_id": "20658870",
                        "start_number": "7",
                        "entry_program_number": "7",
                        "start_position": "7",
                        "coupled_indicator": 0,
                        "decoupled_number": "7",
                        "horse_id": "1155029",
                        "horse_name": "Runaway Maxi",
                        "entry_status": 1,
                        "equipment_code": "",
                        "equipment_description": "",
                        "weight_value": "120",
                        "weight_unit": "lbs",
                        "jockey_id": "122713",
                        "jockey_name": "Jose Luis Campos",
                        "starting_price_fraction": "",
                        "starting_price_percentage": 0,
                        "fav_pos": None,
                        "fav_joint": None,
                        "final_position": "",
                        "dead_heat": None,
                        "disqualified": False,
                        "amended_position": None,
                        "tpd_runner_id": 0,
                        "historical_price_data": [
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:35:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658864",
                                "timestamp": "2025-08-07T19:36:26+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658865",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658866",
                                "timestamp": "2025-08-07T19:32:25+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658867",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658867",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658868",
                                "timestamp": "2025-08-07T19:35:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:30:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658869",
                                "timestamp": "2025-08-07T19:31:23+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:28:05+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:29:07+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                            {
                                "entry_id": "20658870",
                                "timestamp": "2025-08-07T19:30:22+00:00",
                                "price_fraction": "",
                                "price_percentage": 0,
                                "market": "1",
                            },
                        ],
                    },
                ],
            }
        ],
    }
]
